import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ThemeRegistry from './theme-registry';
import { UserContextProvider } from '@/context/userContext';
import AuthProvider from '@/auth/auth-provider';
import Header from '@/components/header/header';
import Footer from '@/components/footer';
import { Box } from '@mui/material';

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@600&display=swap' rel='stylesheet' />
      </head>
      <Box component='body' position='relative'>
        <ThemeRegistry options={{ key: 'mui' }}>
          <UserContextProvider>
            <Header />
            <AuthProvider>
              {children}
            </AuthProvider>
            <Footer />
          </UserContextProvider>
        </ThemeRegistry>
      </Box>
    </html>
  )
}
