import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ThemeRegistry from './theme-registry';
import { Container } from '@mui/material';

import initializeFirebase from '@/auth/firebase';
initializeFirebase();

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <Container>
            {children}
          </Container>
        </ThemeRegistry>
      </body>
    </html>
  )
}
